vertexai: Add Intro to the Vertex AI library
langchain-ai/langchain-google pull request #660
Opened 2024-12-22 09:50 UTC by SauravP97

## PR Description

Added intro to the `Vertex AI` library.
Took reference from the Google Gen AI library: https://python.langchain.com/api_reference/google_genai/index.html

Rendered DocString looks like this: 
<img width="867" alt="Screenshot 2024-12-22 at 3 13 21 PM" src="https://github.com/user-attachments/assets/d83d3040-2083-4cb3-8108-bc1e320649a2" />

Tagging @lkuligin for review.

## Type

📖 Documentation

2025-01-07 09:05 UTC, lkuligin requested changes

2025-01-07 09:05 UTC, lkuligin commented on libs/vertexai/langchain_google_vertexai/__init__.py
> +`ChatVertexAI` class exposes models such as `gemini-pro` and `chat-bison`.
Palm is deprecated, not sure we should mention it.

2025-01-07 09:05 UTC, lkuligin commented on libs/vertexai/langchain_google_vertexai/__init__.py
> +## Chat Models
Let's mention also all models from Model Garden (MaaS and deployed on MG) and other integrations that are exposed in this package, please (like vector stores).

2025-01-07 13:23 UTC, SauravP97 commented on libs/vertexai/langchain_google_vertexai/__init__.py
> +`ChatVertexAI` class exposes models such as `gemini-pro` and `chat-bison`.
I don't see Palm in Model Garden supported Models. I can see Llama and Mistral only.
Please let me know if documentation for Palm needs to be added.

2025-01-07 13:24 UTC, SauravP97 commented on libs/vertexai/langchain_google_vertexai/__init__.py
> +## Chat Models
Sure, I have added documentation for supported models in Model Garden i.e. Mistral and Llama.
I have also added documentation for the Vector Stores.

2025-01-09 09:02 UTC, lkuligin commented on libs/vertexai/langchain_google_vertexai/__init__.py
> +## Supported Models (MaaS: Model-as-a-Service)
let's start with a short description of all supported integration (and a difference between them, please). So that a user doesn't get an impression that only Llama and Mistarl are supported.
You can find a full list here: https://github.com/langchain-ai/langchain-google/blob/bd24d5097aa4a8a145b22fbca305652ded3df626/libs/vertexai/langchain_google_vertexai/__init__.py#L52 (we don't need to mention things like SafetySettings), but let's mention all relevant Vertex AI integrations, please.

2025-01-10 09:01 UTC, SauravP97 commented on libs/vertexai/langchain_google_vertexai/__init__.py
> +## Supported Models (MaaS: Model-as-a-Service)
Thanks for the review comment, looks like some integrated models were left in my PR. I have added those.

A short description of my recent commit.

1. Added Gemma models integration documentation
2. Added Vision models integration documentation
3. Added a difference between Chat model and Base model for the readers to understand our different flavors of models.

2025-01-13 16:26 UTC, lkuligin approved these changes

2025-01-13 16:27 UTC, merged